### ISSUE TITLE
Selection of different Country Twice Error

### ISSUE THREAD

**Issue by sylvbravo** [iamevansobeng/country_state_picker#2]
I installed this package in my project, when I selected country for the first time there was no issue, but when I tried selecting it again this is the error I got in the state dropdown menu. If you select a country, and then you select a state, now try to select a different country without leaving the current screen

![Screenshot_20231116-170230](https://github.com/iamevansobeng/country_state_picker/assets/103633836/d8fae0d8-3717-4e7c-9ed1-cd77d362c0a1)

**Comment by iamevansobeng** [comment]
Sorry for the late response. How are you using it
